# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-08 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
