# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160408_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=b'/static/img/img.jpg', upload_to=b'blah'),
        ),
        migrations.AddField(
            model_name='article',
            name='primary_color',
            field=models.CharField(default=b'None', max_length=128, null=True),
        ),
    ]
