# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160416_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=b'/static/images/data.png', upload_to=b'/static/images'),
        ),
    ]
