# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160416_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=b'data.png', upload_to=b'images'),
        ),
    ]
