# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160416_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
    ]
