# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_alt',
            field=models.CharField(default=b'image', max_length=128),
        ),
    ]
