# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160417_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('last_saved', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
